# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_herrr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Herrr',
        ),
    ]
