# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_delete_herrr'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
